export const getQuoteConfig = {
  initialValues: { address: "" },
  inputs: {
    address: {
      name: "address",
      placeholder: "Enter Address",
    },
  },
  options: {
    suggestions: [
      {
        street_line: "3331 1/2 109th St",
        secondary: "",
        city: "Urbandale",
        state: "IA",
        zipcode: "50322",
        entries: 0,
      },
      {
        street_line: "3331 1/2 109th St",
        secondary: "",
        city: "Urbandale",
        state: "IA",
        zipcode: "50322",
        entries: 0,
      },
      {
        street_line: "3331 1/2 109th St",
        secondary: "",
        city: "Urbandale",
        state: "IA",
        zipcode: "50322",
        entries: 0,
      },
      {
        street_line: "3331 1/2 109th St",
        secondary: "",
        city: "Urbandale",
        state: "IA",
        zipcode: "50322",
        entries: 0,
      },
      {
        street_line: "3331 1/2 109th St",
        secondary: "",
        city: "Urbandale",
        state: "IA",
        zipcode: "50322",
        entries: 0,
      },
      {
        street_line: "3331 1/2 109th St",
        secondary: "",
        city: "Urbandale",
        state: "IA",
        zipcode: "50322",
        entries: 0,
      },
      {
        street_line: "3331 1/2 109th St",
        secondary: "",
        city: "Urbandale",
        state: "IA",
        zipcode: "50322",
        entries: 0,
      },
      {
        street_line: "3331 1/2 109th St",
        secondary: "",
        city: "Urbandale",
        state: "IA",
        zipcode: "50322",
        entries: 0,
      },
      {
        street_line: "3331 1/2 109th St",
        secondary: "",
        city: "Urbandale",
        state: "IA",
        zipcode: "50322",
        entries: 0,
      },
    ],
  },
};
