import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import '../globals.css';
import StoreProvider from '@/app/StoreProvider';
import DashboardLayout from '@/components/dashboard/DashboardLayout';

const dm_sans = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dm_sans.className + 'box-border h-screen w-screen'}>
        <StoreProvider>
          <DashboardLayout>{children}</DashboardLayout>
        </StoreProvider>
      </body>
    </html>
  );
}
