import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import StoreProvider from "./StoreProvider";

const dm_sans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dm_sans.className + "w-screen h-screen box-border"}>
        <Navbar />
        <div className="bg-anti-white w-full h-full pt-20 overflow-auto">
          <StoreProvider>{children}</StoreProvider>
        </div>
      </body>
    </html>
  );
}
