import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import '../globals.css';
import Navbar from '@/components/common/Navbar';
import StoreProvider from '@/app/StoreProvider';

const dm_sans = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dm_sans.className + 'box-border h-screen w-screen'}>
        <Navbar />
        <div className="h-full w-full overflow-auto bg-anti-white pt-20">
          <Toaster
            position="top-center"
            gutter={8}
            containerStyle={{ top: '6rem' }}
            toastOptions={{ className: 'w-96' }}
          />
          <StoreProvider>{children}</StoreProvider>
        </div>
      </body>
    </html>
  );
}
